### ISSUE TITLE
Is this still mantained?

### ISSUE THREAD

**Issue by nickimbo** [Julli4n/roblox-bat#2]
I've tested it and didnt work on api:
https://apis.roblox.com/discovery-api/omni-recommendation

method is POST.

**Comment by Julli4n** [comment]
It's still maintained, Roblox hasn't made any changes to it recently.

**Comment by nickimbo** [comment]
> It's still maintained, Roblox hasn't made any changes to it recently.

idk didnt work for me

**Comment by Julli4n** [comment]
If the code is not being run through the console or through NodeJS but a key is not provided then it probably doesn't work. Otherwise, this module is being used in RoSeal and works fine for fetching it.
